export const ENABLE_LOGGING = false;

export const PLAYER_SPEED = 80;
export const PLAYER_INVULNERABLE_AFTER_HIT_DURATION = 1000;
export const PLAYER_HURT_PUSH_BACK_SPEED = 50;
export const PLAYER_START_MAX_HEALTH = 10;

export const ENEMY_SPIDER_SPEED = 80;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MIN = 500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_MAX = 1500;
export const ENEMY_SPIDER_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_SPIDER_PUSH_BACK_SPEED = 50;
export const ENEMY_SPIDER_MAX_HEALTH = 2;


export const ENEMY_WISP_SPEED = 50;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_X = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_SCALE_Y = 1.2;
export const ENEMY_WISP_PULSE_ANIMATION_DURATION = 500;
export const ENEMY_WISP_MAX_HEALTH = 1;


export const HURT_PUSH_BACK_DELAY = 200;

// Zombie enemy configuration
export const ENEMY_ZOMBIE_SPEED = 40;
export const ENEMY_ZOMBIE_CHANGE_DIRECTION_DELAY_MIN = 800;
export const ENEMY_ZOMBIE_CHANGE_DIRECTION_DELAY_MAX = 2000;
export const ENEMY_ZOMBIE_CHANGE_DIRECTION_DELAY_WAIT = 200;
export const ENEMY_ZOMBIE_PUSH_BACK_SPEED = 40;
export const ENEMY_ZOMBIE_MAX_HEALTH = 3;
export const ENEMY_ZOMBIE_INVULNERABLE_AFTER_HIT_DURATION = 500;
// maximum distance (px) at which zombie will chase the player; beyond this it stops pursuing
export const ENEMY_ZOMBIE_CHASE_RADIUS = 220;